version: '3.7'

services:
  hub:
    image: registry.digitalocean.com/REGISTRY_NAME/hub:latest
    restart: always
    env_file:
      - prod.env
    environment:
      - MONGO_URI=mongodb://root:toor@mongo:27017
    ports:
      - "80:80"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    volumes:
      - "./data:/data/db"

#  watchtower:
#    image: containrrr/watchtower
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /root/.docker/config.json:/config.json
#    command: --interval 1