name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      DOCKER_IMAGE: hub
      DOCKER_TAG: ${{ github.sha }}
      DOCKER_TARGET_PLATFORM: linux/amd64 # ,linux/386,linux/arm/v7,linux/arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Docker login DigitalOcean
        run: doctl registry login --expiry-seconds 600
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          platforms: ${{ env.DOCKER_TARGET_PLATFORM }}
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
          secrets: |
            "ADMIN_LIST=${{ secrets.ADMIN_LIST }}"
            "ETB_TOKEN_ADDRESS=${{ secrets.ETB_TOKEN_ADDRESS }}"
            "MONGO_URI=${{ secrets.MONGO_URI }}"
            "MULTICALL_ADDRESS=${{ secrets.MULTICALL_ADDRESS }}"
            "PINATA_API_KEY=${{ secrets.PINATA_API }}"
            "PINATA_SECRET_KEY=${{ secrets.PINATA_SECRET }}"
            "RPC_API=${{ secrets.RPC_API }}"